version: '3.8'
services:
  taboo:
    container_name: Taboo
    image: theprogrammershangout/taboo:latest
    volumes:
      - type: bind
        source: ./config
        target: /config
    restart: always
    env_file:
      - .env