version: '3.8'
services:
  taboo:
    container_name: Taboo
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - type: bind
        source: ./config/config.json
        target: /config/config.json
    restart: always
    env_file:
      - .env

volumes:
  app: